

// import { Nav } from '@/layout/Nav'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import { Providers } from '../redux/provider'
import { Prelayout } from './Prelayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tic Tac Toe',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Prelayout>
              {children}  
        </Prelayout>
            
      </body>
    </html>
  )
}
